# Generated by Django 6.1 on 2026-08-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publicado', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_el'],
            },
        ),
    ]
